[phases.setup]
nixPkgs = ['nodejs_20', 'php83', 'php83Packages.composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-interaction',
    'npm install',
    'touch resources/js/ziggy.js'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan storage:link || true'
]

[phases.deploy]
cmds = [
    'php artisan migrate --force'
]

[start]
cmd = 'SESSION_DRIVER=file bash start.sh'
