[phases.setup]
nixPkgs = ['nodejs_20', 'php83', 'php83Packages.composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-interaction',
    'npm install',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan storage:link || true'
]

[start]
cmd = 'php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'
