[phases.setup]
nixPkgs = ['nodejs_20', 'php83', 'php83Packages.composer', 'bash']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-interaction',
    'npm install',
    'touch resources/js/ziggy.js'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan storage:link || true'
]

[start]
cmd = 'bash -x start.sh'
